language: minimal
dist: bionic
sudo: false

services:
  - docker

install:
  - docker-compose -f spec/docker-compose.yml run --rm shards

script:
  - docker-compose -f spec/docker-compose.yml run --rm spec
