services:
  app: &crystal
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://username:password@db:5432/shield_spec
      SKIP_CREATE_DB: "true"
    image: crystallang/crystal:0.36.1-alpine
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
  db:
    environment:
      POSTGRES_DB: shield_spec
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    image: postgres:12.5-alpine
  shards:
    <<: *crystal
    command: 'sh -c "shards update"'
    depends_on: []
    environment: {}
  spec:
    <<: *crystal
    command: 'sh -c "crystal spec"'
version: "2.4"
