services:
  db:
    environment:
      POSTGRES_DB: shield_spec
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    image: postgres:12.3-alpine
  spec:
    command: 'sh -c "cd /var/www/html && crystal spec"'
    depends_on:
      - db
    environment:
      APP_DOMAIN: http://localhost:5000
      DATABASE_URL: postgres://username:password@db:5432/shield_spec
      SECRET_KEY_BASE: XeqAgSy5QQ+dWe8ruOBUMrz9XPbPZ7chPVtz2ecDGss=
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "5000"
      SKIP_CREATE_DB: "yes"
    image: crystallang/crystal:0.35.1-alpine
    volumes:
      - ..:/var/www/html
    working_dir: /var/www/html
version: "2.4"
